local config = require("yaml-schema-selector.config")

describe("config.build", function()
  it("errors on a non-table opts", function()
    assert.has_error(function()
      config.build("nope")
    end)
  end)

  it("errors when server_name is empty", function()
    assert.has_error(function()
      config.build({ server_name = "" })
    end)
  end)

  it("errors when schemas values are not strings", function()
    assert.has_error(function()
      config.build({ schemas = { a = 1 } })
    end)
  end)

  it("errors when max_parse_bytes is negative", function()
    assert.has_error(function()
      config.build({ max_parse_bytes = -1 })
    end)
  end)

  it("applies defaults on top of the given options", function()
    local cfg = config.build({ schemas = { a = "b" } })
    assert.equals("yamlls", cfg.server_name)
    assert.same({ a = "b" }, cfg.schemas)
    assert.equals(1024 * 1024, cfg.max_parse_bytes)
  end)

  it("does not mutate the defaults table across calls", function()
    config.build({ schemas = { a = "b" } })
    assert.same({}, config.defaults.schemas)
  end)
end)
