local config = require("yaml-schema-selector.config")

describe("config.build", function()
  it("errors when select is missing", function()
    assert.has_error(function()
      config.build({})
    end)
  end)

  it("errors when select is not a function", function()
    assert.has_error(function()
      config.build({ select = "nope" })
    end)
  end)

  it("errors on a non-table opts", function()
    assert.has_error(function()
      config.build("nope")
    end)
  end)

  it("errors when server_name is empty", function()
    assert.has_error(function()
      config.build({ select = function() end, server_name = "" })
    end)
  end)

  it("errors when schemas values are not strings", function()
    assert.has_error(function()
      config.build({ select = function() end, schemas = { a = 1 } })
    end)
  end)

  it("errors when max_parse_bytes is negative", function()
    assert.has_error(function()
      config.build({ select = function() end, max_parse_bytes = -1 })
    end)
  end)

  it("applies defaults on top of the given options", function()
    local fn = function() end
    local cfg = config.build({ select = fn, schemas = { a = "b" } })
    assert.equals("yamlls", cfg.server_name)
    assert.same({ a = "b" }, cfg.schemas)
    assert.equals(fn, cfg.select)
    assert.equals(1024 * 1024, cfg.max_parse_bytes)
  end)

  it("does not mutate the defaults table across calls", function()
    config.build({ select = function() end, schemas = { a = "b" } })
    assert.same({}, config.defaults.schemas)
  end)
end)
